### ISSUE TITLE
BitCoin exchange rate

### ISSUE THREAD

**Issue by wjcrowcroft** [currencybot/open-exchange-rates#16]
Was chatting to colleagues last night and one suggested adding virtual currencies to the open exchange rates data - BitCoin springs to mind, but also potentially Linden Dollars (Second Life) and any other currency with a real foreign exchange potential.

I think it's a cool idea, and may in fact be useful to people who allow users to pay in BitCoin - the difficulty would be finding a canonical source for the exchange rate, when (as far as I know) every BitCoin exchange buys/sells at different prices. 

Anyone have any ideas or thoughts on this?

**Comment by tommoor** [comment]
No thoughts on where to get the data from (presumably Linden dollars would be easy enough?) - But I do think this is a great idea that would set OER apart.

Infact don't you have Coinbase as a user now? I'm sure there could be some mutual data-exchange opportunities there :-)

**Comment by wjcrowcroft** [comment]
Hey mate!

Bitcoin's been in the API for a month now! Forgiven for missing it, I haven't (yet) made a blog post about it :)

**Comment by tommoor** [comment]
Oh? Lovely, sounds like this is a closed issue then!

**Comment by wjcrowcroft** [comment]
Good call. Catch you later :+1:
