### ISSUE TITLE
Support for RMB (Chinese yuan)?

### ISSUE THREAD

**Issue by sanity** [currencybot/open-exchange-rates#22]
Hi, I was surprised to see that the API doesn't appear to have an exchange rate for the Chinese yuan (code RMB).  Could this be supported?

Thanks!

**Comment by wjcrowcroft** [comment]
The [ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) code for Chinese Yuan ([Renminbi](http://en.wikipedia.org/wiki/Renminbi)) is actually **CNY**, not **RMB** - as far as I'm aware. Confusing, I know!

**CNY** is given in the exchange rates. I was considering adding it as **RMB**as well, but as far as I'm aware, they're actually treated separately..

Happy to be corrected by experts on this one, as Chinese currency seems a bit of an enigma to me.

**Comment by sanity** [comment]
Doh!  No, you're right, thanks.
