### ISSUE TITLE
ZWD available in currencies.json but not in latest.json

### ISSUE THREAD

**Issue by JosephSilber** [currencybot/open-exchange-rates#34]
The title basically says it all.

In [currencies.json](https://raw.github.com/currencybot/open-exchange-rates/master/currencies.json), there's an entry as follows:

```
 ZWD: "Zimbabwean Dollar (1980-2008)"
```

But in [latest.json](https://github.com/currencybot/open-exchange-rates/blob/master/latest.json) it's nowhere to be found.

**Comment by wjcrowcroft** [comment]
It's available in historical files, hence needs to be in currencies.json, but no longer exists AFAIK.
