### ISSUE TITLE
timestamp for historical data request for 2013-01-01 is not correct

### ISSUE THREAD

**Issue by tkremmel** [currencybot/open-exchange-rates#37]
Hi,

I'm making the following request to your api:

http://openexchangerates.org/api/historical/2013-01-01.json

which returns me a json object as seen below, with the timestamp '1357084809'. This unix timestamp converts to Wed, 02 Jan 2013 00:00:09 GMT, whereas I would have expected to receive a timestamp for the first of January. Is this a bug or do I experience a timezone issue? I'm using a python client to access your api: https://github.com/metglobal/django-exchange

If I m doing the following request: http://openexchangerates.org/api/historical/2013-01-05.json
the timestamp is set to 1357426809 which converts to Sat, 05 Jan 2013 23:00:09 GMT, which is what I would have expected.

{u'timestamp': 1357084809, u'base': u'USD', u'rates': {u'DZD': 78.203501, u'NAD': 8.472121, ....}

**Comment by wjcrowcroft** [comment]
Hi – thanks very much for reporting this. Have you experienced it on any other dates?

I will take a look into it now.

**Comment by tkremmel** [comment]
Hi - thanks for taking a look at it, and thanks for this great API! I just started using it yesterday, creating my own fork of django-exchange, and for now, this was the only date I experienced this issue, whereas I tried only a few dates in between January and February 2013.

**Comment by wjcrowcroft** [comment]
Cheers for the info. This one's been fixed, and I'm working on an update that will make sure it doesn't happen again (or for any other previous historical dates)

Best of luck and let me know how you get on with the django-exchange fork :+1:

**Comment by tkremmel** [comment]
Perfect! I checked it and the result is now as expected :)

http://openexchangerates.org/api/historical/2013-01-01.json
{u'timestamp': 1357084740, u'base': u'USD', u'rates': {u'DZD': ..
which resolves to:
Tue, 01 Jan 2013 23:59:00 GMT

The django-exchange fork is going fine. I added some code to fetch and save the historical exchange rates from the api.

All the best,
Thomas
